### ISSUE TITLE
UP, 付费求个YoutubeToBilibili的配置

### ISSUE THREAD

**Issue by lionderful** [HarukaKinen/Twitsu#1]
付费求个自动搬运配置, 
你的YoutubeToBilibili用不了, youtube_dl 限速, 不能正常下载, 需要集成yt-dlp
也懒得折腾了

**Comment by NukoOoOoOoO** [comment]
YouTubeToBilibili是我写的。

配置文件我已经写得很清楚了，看不懂我觉得可以让别人帮你理解下，或者我用英文来写。再不行就看源代码，毕竟是开源的。

限速我用着没问题，看起来是你的问题。
